spring:
  datasource:
    url: "jdbc:postgresql://localhost:12432/postgres"
    username: "orchestratordb"
    password: "orchestratordb"
  r2dbc:
    url: "r2dbc:postgresql://localhost:12432/postgres"
    username: "orchestratordb"
    password: "orchestratordb"
    pool:
      initial-size: 10
      max-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  flyway:
    baseline-on-migrate: true
    clean-disabled: false
  # Embedded ActiveMQ Configuration Example

  # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 5
      max-concurrency: 10
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: PERSISTENT
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
